; PlatformIO конфигурация для сборки прошивки
[env:nodemcu-32s]
platform = espressif32@3.5.0
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
build_type = release

; Оптимизация размера
build_unflags = -Os
build_flags = -O2

; Дополнительные библиотеки (не требуются, всё в ядре)
; lib_deps =
